// <auto-generated />
using System;
using ExistingDb.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExistingDb.Api.Data.Migrations
{
    [DbContext(typeof(ApiManagementDbContext))]
    [Migration("20260528084558_UseEndUserForMaterialPurchasePrice")]
    partial class UseEndUserForMaterialPurchasePrice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExistingDb.Api.Data.Entities.ApiAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EntityName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("LegacyUserGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("RecordGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecordId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("ApiAuditLogs", (string)null);
                });

            modelBuilder.Entity("ExistingDb.Api.Data.Entities.ApiFieldPermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceFieldId")
                        .HasColumnType("int");

                    b.Property<bool>("CanCreate")
                        .HasColumnType("bit");

                    b.Property<bool>("CanUpdate")
                        .HasColumnType("bit");

                    b.Property<string>("ReadMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RoleId", "ResourceFieldId");

                    b.HasIndex("ResourceFieldId");

                    b.ToTable("ApiFieldPermissions", (string)null);
                });

            modelBuilder.Entity("ExistingDb.Api.Data.Entities.ApiPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ApiPermissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "admin",
                            Code = "admin.users.manage",
                            Name = "Manage API users"
                        },
                        new
                        {
                            Id = 2,
                            Category = "admin",
                            Code = "admin.roles.manage",
                            Name = "Manage API roles"
                        },
                        new
                        {
                            Id = 3,
                            Category = "admin",
                            Code = "admin.permissions.read",
                            Name = "Read permissions"
                        },
                        new
                        {
                            Id = 4,
                            Category = "audit",
                            Code = "audit.read",
                            Name = "Read audit logs"
                        },
                        new
                        {
                            Id = 5,
                            Category = "customers",
                            Code = "customers.read",
                            Name = "Read customers"
                        },
                        new
                        {
                            Id = 6,
                            Category = "customers",
                            Code = "customers.create",
                            Name = "Create customers"
                        },
                        new
                        {
                            Id = 7,
                            Category = "customers",
                            Code = "customers.update",
                            Name = "Update customers"
                        },
                        new
                        {
                            Id = 8,
                            Category = "materials",
                            Code = "materials.read",
                            Name = "Read materials"
                        },
                        new
                        {
                            Id = 9,
                            Category = "materials",
                            Code = "materials.update",
                            Name = "Update materials"
                        },
                        new
                        {
                            Id = 10,
                            Category = "bills",
                            Code = "bills.read",
                            Name = "Read bills"
                        },
                        new
                        {
                            Id = 11,
                            Category = "bills",
                            Code = "bills.create",
                            Name = "Create bills"
                        },
                        new
                        {
                            Id = 12,
                            Category = "bills",
                            Code = "bills.post",
                            Name = "Post bills"
                        },
                        new
                        {
                            Id = 13,
                            Category = "accounts",
                            Code = "accounts.read",
                            Name = "Read accounts"
                        },
                        new
                        {
                            Id = 14,
                            Category = "accounts",
                            Code = "entries.read",
                            Name = "Read entries"
                        },
                        new
                        {
                            Id = 15,
                            Category = "inventory",
                            Code = "inventory.read",
                            Name = "Read inventory balances"
                        });
                });

            modelBuilder.Entity("ExistingDb.Api.Data.Entities.ApiRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("ApiRefreshTokens", (string)null);
                });

            modelBuilder.Entity("ExistingDb.Api.Data.Entities.ApiResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ApiResources", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "customers",
                            Name = "Customers"
                        },
                        new
                        {
                            Id = 2,
                            Code = "materials",
                            Name = "Materials"
                        },
                        new
                        {
                            Id = 3,
                            Code = "bills",
                            Name = "Bills"
                        },
                        new
                        {
                            Id = 4,
                            Code = "billItems",
                            Name = "Bill items"
                        },
                        new
                        {
                            Id = 5,
                            Code = "accounts",
                            Name = "Accounts"
                        },
                        new
                        {
                            Id = 6,
                            Code = "inventory",
                            Name = "Inventory"
                        });
                });

            modelBuilder.Entity("ExistingDb.Api.Data.Entities.ApiResourceField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DefaultCanCreate")
                        .HasColumnType("bit");

                    b.Property<bool>("DefaultCanUpdate")
                        .HasColumnType("bit");

                    b.Property<string>("DefaultReadMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("bit");

                    b.Property<string>("MaskingStrategy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId", "FieldName")
                        .IsUnique();

                    b.ToTable("ApiResourceFields", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefaultCanCreate = false,
                            DefaultCanUpdate = false,
                            DefaultReadMode = "Mask",
                            DisplayName = "Primary phone",
                            FieldName = "Phone1",
                            IsSensitive = true,
                            MaskingStrategy = "Phone",
                            ResourceId = 1
                        },
                        new
                        {
                            Id = 2,
                            DefaultCanCreate = false,
                            DefaultCanUpdate = false,
                            DefaultReadMode = "Mask",
                            DisplayName = "Secondary phone",
                            FieldName = "Phone2",
                            IsSensitive = true,
                            MaskingStrategy = "Phone",
                            ResourceId = 1
                        },
                        new
                        {
                            Id = 3,
                            DefaultCanCreate = false,
                            DefaultCanUpdate = false,
                            DefaultReadMode = "Mask",
                            DisplayName = "Mobile phone",
                            FieldName = "Mobile",
                            IsSensitive = true,
                            MaskingStrategy = "Phone",
                            ResourceId = 1
                        },
                        new
                        {
                            Id = 4,
                            DefaultCanCreate = false,
                            DefaultCanUpdate = false,
                            DefaultReadMode = "Mask",
                            DisplayName = "Email",
                            FieldName = "EMail",
                            IsSensitive = true,
                            MaskingStrategy = "Email",
                            ResourceId = 1
                        },
                        new
                        {
                            Id = 5,
                            DefaultCanCreate = false,
                            DefaultCanUpdate = false,
                            DefaultReadMode = "Deny",
                            DisplayName = "Linked account",
                            FieldName = "AccountGUID",
                            IsSensitive = true,
                            MaskingStrategy = "Full",
                            ResourceId = 1
                        },
                        new
                        {
                            Id = 6,
                            DefaultCanCreate = false,
                            DefaultCanUpdate = false,
                            DefaultReadMode = "Deny",
                            DisplayName = "Average price",
                            FieldName = "AvgPrice",
                            IsSensitive = true,
                            MaskingStrategy = "Full",
                            ResourceId = 2
                        },
                        new
                        {
                            Id = 7,
                            DefaultCanCreate = false,
                            DefaultCanUpdate = false,
                            DefaultReadMode = "Deny",
                            DisplayName = "Last price",
                            FieldName = "LastPrice",
                            IsSensitive = true,
                            MaskingStrategy = "Full",
                            ResourceId = 2
                        },
                        new
                        {
                            Id = 8,
                            DefaultCanCreate = false,
                            DefaultCanUpdate = false,
                            DefaultReadMode = "Mask",
                            DisplayName = "Wholesale SYP price",
                            FieldName = "Whole",
                            IsSensitive = true,
                            MaskingStrategy = "Full",
                            ResourceId = 2
                        },
                        new
                        {
                            Id = 9,
                            DefaultCanCreate = false,
                            DefaultCanUpdate = false,
                            DefaultReadMode = "Deny",
                            DisplayName = "Purchase USD price",
                            FieldName = "EndUser",
                            IsSensitive = true,
                            MaskingStrategy = "Full",
                            ResourceId = 2
                        },
                        new
                        {
                            Id = 10,
                            DefaultCanCreate = true,
                            DefaultCanUpdate = true,
                            DefaultReadMode = "Allow",
                            DisplayName = "Bill total",
                            FieldName = "Total",
                            IsSensitive = true,
                            MaskingStrategy = "Full",
                            ResourceId = 3
                        },
                        new
                        {
                            Id = 11,
                            DefaultCanCreate = false,
                            DefaultCanUpdate = false,
                            DefaultReadMode = "Mask",
                            DisplayName = "Total discount",
                            FieldName = "TotalDisc",
                            IsSensitive = true,
                            MaskingStrategy = "Full",
                            ResourceId = 3
                        },
                        new
                        {
                            Id = 12,
                            DefaultCanCreate = false,
                            DefaultCanUpdate = false,
                            DefaultReadMode = "Deny",
                            DisplayName = "Profits",
                            FieldName = "Profits",
                            IsSensitive = true,
                            MaskingStrategy = "Full",
                            ResourceId = 3
                        },
                        new
                        {
                            Id = 13,
                            DefaultCanCreate = true,
                            DefaultCanUpdate = true,
                            DefaultReadMode = "Allow",
                            DisplayName = "Item price",
                            FieldName = "Price",
                            IsSensitive = true,
                            MaskingStrategy = "Full",
                            ResourceId = 4
                        },
                        new
                        {
                            Id = 14,
                            DefaultCanCreate = false,
                            DefaultCanUpdate = false,
                            DefaultReadMode = "Mask",
                            DisplayName = "Item discount",
                            FieldName = "Discount",
                            IsSensitive = true,
                            MaskingStrategy = "Full",
                            ResourceId = 4
                        },
                        new
                        {
                            Id = 15,
                            DefaultCanCreate = false,
                            DefaultCanUpdate = false,
                            DefaultReadMode = "Deny",
                            DisplayName = "Item profits",
                            FieldName = "Profits",
                            IsSensitive = true,
                            MaskingStrategy = "Full",
                            ResourceId = 4
                        },
                        new
                        {
                            Id = 16,
                            DefaultCanCreate = false,
                            DefaultCanUpdate = false,
                            DefaultReadMode = "Mask",
                            DisplayName = "Debit",
                            FieldName = "Debit",
                            IsSensitive = true,
                            MaskingStrategy = "Full",
                            ResourceId = 5
                        },
                        new
                        {
                            Id = 17,
                            DefaultCanCreate = false,
                            DefaultCanUpdate = false,
                            DefaultReadMode = "Mask",
                            DisplayName = "Credit",
                            FieldName = "Credit",
                            IsSensitive = true,
                            MaskingStrategy = "Full",
                            ResourceId = 5
                        },
                        new
                        {
                            Id = 18,
                            DefaultCanCreate = false,
                            DefaultCanUpdate = false,
                            DefaultReadMode = "Deny",
                            DisplayName = "Opening debit",
                            FieldName = "InitDebit",
                            IsSensitive = true,
                            MaskingStrategy = "Full",
                            ResourceId = 5
                        },
                        new
                        {
                            Id = 19,
                            DefaultCanCreate = false,
                            DefaultCanUpdate = false,
                            DefaultReadMode = "Deny",
                            DisplayName = "Opening credit",
                            FieldName = "InitCredit",
                            IsSensitive = true,
                            MaskingStrategy = "Full",
                            ResourceId = 5
                        },
                        new
                        {
                            Id = 20,
                            DefaultCanCreate = true,
                            DefaultCanUpdate = true,
                            DefaultReadMode = "Allow",
                            DisplayName = "Quantity",
                            FieldName = "Qty",
                            IsSensitive = true,
                            MaskingStrategy = "Full",
                            ResourceId = 6
                        },
                        new
                        {
                            Id = 21,
                            DefaultCanCreate = false,
                            DefaultCanUpdate = false,
                            DefaultReadMode = "Mask",
                            DisplayName = "Book quantity",
                            FieldName = "Book",
                            IsSensitive = true,
                            MaskingStrategy = "Full",
                            ResourceId = 6
                        },
                        new
                        {
                            Id = 22,
                            DefaultCanCreate = false,
                            DefaultCanUpdate = false,
                            DefaultReadMode = "Mask",
                            DisplayName = "Wholesale USD price",
                            FieldName = "Half",
                            IsSensitive = true,
                            MaskingStrategy = "Full",
                            ResourceId = 2
                        });
                });

            modelBuilder.Entity("ExistingDb.Api.Data.Entities.ApiRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("ApiRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Full API administration access.",
                            IsSystemRole = true,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Operational management access.",
                            IsSystemRole = true,
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Standard API user access.",
                            IsSystemRole = true,
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Read-only API access.",
                            IsSystemRole = true,
                            Name = "Viewer",
                            NormalizedName = "VIEWER"
                        });
                });

            modelBuilder.Entity("ExistingDb.Api.Data.Entities.ApiRolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("ApiRolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 15
                        });
                });

            modelBuilder.Entity("ExistingDb.Api.Data.Entities.ApiUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("LegacyUserGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LegacyUserGuid");

                    b.HasIndex("NormalizedEmail");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique();

                    b.ToTable("ApiUsers", (string)null);
                });

            modelBuilder.Entity("ExistingDb.Api.Data.Entities.ApiUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("ApiUserRoles", (string)null);
                });

            modelBuilder.Entity("ExistingDb.Api.Data.Entities.ApiFieldPermission", b =>
                {
                    b.HasOne("ExistingDb.Api.Data.Entities.ApiResourceField", "ResourceField")
                        .WithMany("FieldPermissions")
                        .HasForeignKey("ResourceFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExistingDb.Api.Data.Entities.ApiRole", "Role")
                        .WithMany("FieldPermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResourceField");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ExistingDb.Api.Data.Entities.ApiRefreshToken", b =>
                {
                    b.HasOne("ExistingDb.Api.Data.Entities.ApiUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExistingDb.Api.Data.Entities.ApiResourceField", b =>
                {
                    b.HasOne("ExistingDb.Api.Data.Entities.ApiResource", "Resource")
                        .WithMany("Fields")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("ExistingDb.Api.Data.Entities.ApiRolePermission", b =>
                {
                    b.HasOne("ExistingDb.Api.Data.Entities.ApiPermission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExistingDb.Api.Data.Entities.ApiRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ExistingDb.Api.Data.Entities.ApiUserRole", b =>
                {
                    b.HasOne("ExistingDb.Api.Data.Entities.ApiRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExistingDb.Api.Data.Entities.ApiUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExistingDb.Api.Data.Entities.ApiPermission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ExistingDb.Api.Data.Entities.ApiResource", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("ExistingDb.Api.Data.Entities.ApiResourceField", b =>
                {
                    b.Navigation("FieldPermissions");
                });

            modelBuilder.Entity("ExistingDb.Api.Data.Entities.ApiRole", b =>
                {
                    b.Navigation("FieldPermissions");

                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ExistingDb.Api.Data.Entities.ApiUser", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
