#Requires -Version 5.1
#Requires -RunAsAdministrator
<#
.SYNOPSIS
  Install ExistingDb.Api as a Windows service (auto-start on boot).

.EXAMPLE
  .\deploy\api\install-windows-service.ps1 -ApiDir D:\AmeenApi\existingdb-api
  .\deploy\api\install-windows-service.ps1 -ApiDir D:\AmeenApi\existingdb-api -Port 5000
#>
param(
    [string]$ApiDir = '',
    [int]$Port = 5000,
    [string]$BindHost = '0.0.0.0',
    [string]$ServiceName = 'JawishExistingDbApi',
    [string]$DisplayName = 'Jawish ExistingDb API'
)

$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\..\lib\common.ps1"

if (-not $ApiDir) {
    $envFile = Join-Path $DeployRoot 'deploy.env'
    if (Test-Path $envFile) {
        $vars = Read-DeployEnv -Path $envFile
        $ApiDir = $vars['API_PUBLISH_DIR']
        if ($vars['API_PORT']) { $Port = [int]$vars['API_PORT'] }
        if ($vars['API_BIND_HOST']) { $BindHost = $vars['API_BIND_HOST'] }
    }
}

if (-not $ApiDir) {
    throw 'ApiDir is required. Example: -ApiDir D:\AmeenApi\existingdb-api'
}

$ApiDir = (Resolve-Path $ApiDir).Path
$dllPath = Join-Path $ApiDir 'ExistingDb.Api.dll'
if (-not (Test-Path $dllPath)) {
    throw "ExistingDb.Api.dll not found in $ApiDir"
}

$dotnet = (Get-Command dotnet -ErrorAction Stop).Source
$starterScript = Join-Path $ApiDir 'start-api-service.ps1'
$urls = "http://${BindHost}:$Port"

$starterContent = @"
# Auto-generated by deploy/api/install-windows-service.ps1
Set-Location '$ApiDir'
`$env:ASPNETCORE_ENVIRONMENT = 'Production'
& '$dotnet' '$dllPath' --urls '$urls'
"@

$utf8Bom = New-Object System.Text.UTF8Encoding $true
[System.IO.File]::WriteAllText($starterScript, $starterContent, $utf8Bom)
Write-Ok "Created $starterScript"

$binPath = "powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$starterScript`""

$existing = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
if ($existing) {
    Write-Warn "Service $ServiceName already exists - stopping and removing"
    if ($existing.Status -eq 'Running') {
        Stop-Service -Name $ServiceName -Force
    }
    sc.exe delete $ServiceName | Out-Null
    Start-Sleep -Seconds 2
}

Write-Step "Creating Windows service: $ServiceName"
New-Service `
    -Name $ServiceName `
    -BinaryPathName $binPath `
    -DisplayName $DisplayName `
    -StartupType Automatic `
    -Description 'ExistingDb.Api - Jawish Amine REST API' | Out-Null

Write-Step 'Starting service'
Start-Service -Name $ServiceName
Start-Sleep -Seconds 3

$svc = Get-Service -Name $ServiceName
Write-Ok "Service status: $($svc.Status)"

$healthUrl = "http://127.0.0.1:$Port/api/health"
Write-Host "Test: $healthUrl" -ForegroundColor Gray
try {
    $health = Invoke-RestMethod -Uri $healthUrl -TimeoutSec 10
    Write-Ok "Health check: $($health.status) / $($health.service)"
} catch {
    Write-Warn "Service is installed but health check failed: $($_.Exception.Message)"
    Write-Host 'Check Event Viewer or run start-api-service.ps1 manually for errors.' -ForegroundColor Yellow
}

Write-Host ''
Write-Host 'Useful commands:' -ForegroundColor Cyan
Write-Host "  Get-Service $ServiceName"
Write-Host "  Restart-Service $ServiceName"
Write-Host "  Stop-Service $ServiceName"
Write-Host "  services.msc   (GUI - set Log On account if SQL login fails)"
