namespace ExistingDb.Api.Contracts.Materials;

public sealed record MaterialResponse(
    Guid MaterialGuid,
    int? RecordNumber,
    string? Name,
    string? MaterialCode,
    string? LatinName,
    string? Barcode,
    string? PrimaryUnit,
    string? PackageUnit,
    double? PackageConversionFactor,
    bool? IsPackageConversionFixed,
    double? WarehouseQuantity,
    object? UnitSalePriceSyp,
    object? UnitSalePriceUsd,
    object? UnitPurchasePriceUsd,
    object? AveragePrice,
    object? LastPrice,
    double? CurrencyRate,
    string? CountryOfOrigin,
    string? Manufacturer,
    string? SizeRange,
    string? MaterialType,
    string? AgeCategory,
    Guid? GroupGuid,
    Guid? ProductImageGuid,
    Guid? CurrencyGuid,
    int? ClassificationType,
    int? SecurityLevel,
    double? UsageFlag,
    bool? IsHidden);

